AWSTemplateFormatVersion: '2010-09-09'
Description: 'Event Ticketing System - API Gateway and Lambda Functions'

Parameters:
  Environment:
    Type: String
    Default: dev
  ProjectName:
    Type: String
    Default: event-ticketing
  BaseStackName:
    Type: String
    Default: event-ticketing-base-dev
  AuthStackName:
    Type: String
    Default: event-ticketing-auth-dev

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - Fn::ImportValue: !Sub '${BaseStackName}-EventsTableArn'
                  - Fn::ImportValue: !Sub '${BaseStackName}-RegistrationsTableArn'
                  - Fn::ImportValue: !Sub '${BaseStackName}-TicketsTableArn'
                  - !Sub
                    - '${TableArn}/index/*'
                    - TableArn:
                        Fn::ImportValue: !Sub '${BaseStackName}-EventsTableArn'
                  - !Sub
                    - '${TableArn}/index/*'
                    - TableArn:
                        Fn::ImportValue: !Sub '${BaseStackName}-RegistrationsTableArn'
                  - !Sub
                    - '${TableArn}/index/*'
                    - TableArn:
                        Fn::ImportValue: !Sub '${BaseStackName}-TicketsTableArn'

  # Create Event Lambda
  CreateEventFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-createEvent-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          EVENTS_TABLE:
            Fn::ImportValue: !Sub '${BaseStackName}-EventsTable'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - Deploy actual code' })
            };
          };

  # List Events Lambda
  ListEventsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-listEvents-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          EVENTS_TABLE:
            Fn::ImportValue: !Sub '${BaseStackName}-EventsTable'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - Deploy actual code' })
            };
          };

  # Get Event Lambda
  GetEventFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-getEvent-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          EVENTS_TABLE:
            Fn::ImportValue: !Sub '${BaseStackName}-EventsTable'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - Deploy actual code' })
            };
          };

  # Create Registration Lambda
  CreateRegistrationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-createRegistration-${Environment}'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          EVENTS_TABLE:
            Fn::ImportValue: !Sub '${BaseStackName}-EventsTable'
          REGISTRATIONS_TABLE:
            Fn::ImportValue: !Sub '${BaseStackName}-RegistrationsTable'
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ message: 'Placeholder - Deploy actual code' })
            };
          };

  # API Gateway REST API
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-api-${Environment}'
      Description: Event Ticketing System API
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Cognito Authorizer
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGateway
      ProviderARNs:
        - Fn::ImportValue: !Sub '${AuthStackName}-UserPoolArn'

  # /events resource
  EventsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: events

  # /events/{id} resource
  EventIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref EventsResource
      PathPart: '{id}'

  # /registrations resource
  RegistrationsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: registrations

  # POST /events
  CreateEventMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref EventsResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateEventFunction.Arn}/invocations'

  # GET /events
  ListEventsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref EventsResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListEventsFunction.Arn}/invocations'

  # GET /events/{id}
  GetEventMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref EventIdResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetEventFunction.Arn}/invocations'

  # POST /registrations
  CreateRegistrationMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref RegistrationsResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref CognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateRegistrationFunction.Arn}/invocations'

  # Lambda Permissions
  CreateEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateEventFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  ListEventsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListEventsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  GetEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetEventFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  CreateRegistrationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateRegistrationFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  # API Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - CreateEventMethod
      - ListEventsMethod
      - GetEventMethod
      - CreateRegistrationMethod
    Properties:
      RestApiId: !Ref ApiGateway

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: !Ref Environment
      Description: !Sub '${Environment} stage'
      TracingEnabled: true

Outputs:
  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref ApiGateway
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'

  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayUrl'

  CreateEventFunctionArn:
    Description: Create Event Lambda ARN
    Value: !GetAtt CreateEventFunction.Arn

  ListEventsFunctionArn:
    Description: List Events Lambda ARN
    Value: !GetAtt ListEventsFunction.Arn

  GetEventFunctionArn:
    Description: Get Event Lambda ARN
    Value: !GetAtt GetEventFunction.Arn

  CreateRegistrationFunctionArn:
    Description: Create Registration Lambda ARN
    Value: !GetAtt CreateRegistrationFunction.Arn
