AWSTemplateFormatVersion: '2010-09-09'
Description: 'Event Ticketing System - Base Infrastructure (DynamoDB, S3, CloudFront)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name
  
  ProjectName:
    Type: String
    Default: event-ticketing
    Description: Project name for resource naming

Resources:
  # ==========================================
  # DynamoDB Tables
  # ==========================================
  
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-events-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: organizerId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OrganizerIndex
          KeySchema:
            - AttributeName: organizerId
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  RegistrationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-registrations-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: registrationId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: registeredAt
          AttributeType: S
        - AttributeName: paymentId
          AttributeType: S
      KeySchema:
        - AttributeName: registrationId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: registeredAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EventIndex
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: registeredAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: PaymentIndex
          KeySchema:
            - AttributeName: paymentId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-tickets-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
        - AttributeName: registrationId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: generatedAt
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: qrCode
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RegistrationIndex
          KeySchema:
            - AttributeName: registrationId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: generatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: EventIndex
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: QRCodeIndex
          KeySchema:
            - AttributeName: qrCode
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ==========================================
  # S3 Buckets
  # ==========================================

  TicketsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-tickets-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOldTickets
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-frontend-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # ==========================================
  # CloudFront Distribution
  # ==========================================

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # ==========================================
  # CloudWatch Log Groups
  # ==========================================

  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}'
      RetentionInDays: 7

Outputs:
  EventsTableName:
    Description: Events DynamoDB Table Name
    Value: !Ref EventsTable
    Export:
      Name: !Sub '${AWS::StackName}-EventsTable'

  EventsTableArn:
    Description: Events DynamoDB Table ARN
    Value: !GetAtt EventsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-EventsTableArn'

  RegistrationsTableName:
    Description: Registrations DynamoDB Table Name
    Value: !Ref RegistrationsTable
    Export:
      Name: !Sub '${AWS::StackName}-RegistrationsTable'

  RegistrationsTableArn:
    Description: Registrations DynamoDB Table ARN
    Value: !GetAtt RegistrationsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RegistrationsTableArn'

  TicketsTableName:
    Description: Tickets DynamoDB Table Name
    Value: !Ref TicketsTable
    Export:
      Name: !Sub '${AWS::StackName}-TicketsTable'

  TicketsTableArn:
    Description: Tickets DynamoDB Table ARN
    Value: !GetAtt TicketsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TicketsTableArn'

  TicketsBucketName:
    Description: S3 Bucket for Tickets
    Value: !Ref TicketsBucket
    Export:
      Name: !Sub '${AWS::StackName}-TicketsBucket'

  TicketsBucketArn:
    Description: S3 Bucket ARN for Tickets
    Value: !GetAtt TicketsBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TicketsBucketArn'

  FrontendBucketName:
    Description: S3 Bucket for Frontend
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  CloudFrontURL:
    Description: CloudFront Distribution URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontURL'
